user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: william
    password: william

url: http://192.168.40.130/

mysql:
  db: trading_system
  host: 192.168.40.130
  password: william
  port: 3306
  user: root

redis:
  host: 192.168.40.130
  port: 6379
  db: 0

jenkins:
  url: http://localhost:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=0cc4e11c529be112b428b5a30ba51295d16e82ecec2013c4160bdf2cd72d527d

qywx_group:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e7c2a250-250d-4654-82d6-93924c08c134